// <auto-generated />
using AI_spotter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AI_spotter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("AI_spotter.Models.Analysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("BiomechanicalData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("BiomechanicalShape")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComparisonResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("AI_spotter.Models.LandmarkData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("Landmarks");
                });

            modelBuilder.Entity("AI_spotter.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CameraAngle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NReps")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("AI_spotter.Models.Analysis", b =>
                {
                    b.HasOne("AI_spotter.Models.Session", "Session")
                        .WithOne("Analysis")
                        .HasForeignKey("AI_spotter.Models.Analysis", "SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AI_spotter.Models.LandmarkData", b =>
                {
                    b.HasOne("AI_spotter.Models.Session", "Session")
                        .WithOne("Landmark")
                        .HasForeignKey("AI_spotter.Models.LandmarkData", "SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AI_spotter.Models.Session", b =>
                {
                    b.Navigation("Analysis");

                    b.Navigation("Landmark");
                });
#pragma warning restore 612, 618
        }
    }
}
